---
- hosts: all
  sudo: True
  user: ansible
  sudo_user: root

  vars_files:
     - variables/common.yml
     - variables/lamp.yml
     - variables/mail.yml
     - variables/private.yml

  tasks:
  - include: tasks/update.yml
  - include: tasks/common.yml
  - include: tasks/devtools.yml 
  - include: tasks/msmtp.yml  
  - include: tasks/lamp.yml
  - include: tasks/secure.yml
  - include: tasks/yii.yml
  - include: tasks/websites.yml

  handlers:
  - include: handlers/lamp.yml
  - include: handlers/munin.yml
  - include: handlers/secure.yml