---
- hosts: local
  sudo: True
  user: stephan
  sudo_user: root

  vars_files:
     - variables/common.yml
     - variables/monitoring.yml
     - variables/php5.yml
     - variables/secure.yml
     - variables/webserver.yml
     - variables/mysql.yml
     - private/variables.yml

  tasks:
  - include: tasks/update.yml
  - include: tasks/common.yml
  - include: tasks/gmailrelay.yml
  - include: tasks/fileserver.yml
  - include: tasks/devtools.yml  
  - include: tasks/php5.yml
  - include: tasks/webserver.yml
  - include: tasks/munin.yml
  - include: tasks/node.yml
  - include: tasks/mysql.yml
  - include: tasks/secure.yml

  handlers:
  - include: handlers/webserver.yml
  - include: handlers/munin.yml
  - include: handlers/secure.yml
  - include: handlers/mysql.yml
  - include: handlers/php5.yml