     - name: Dev | Development software should be installed
       action: apt pkg={{ item }} state=latest
       with_items:
          - make
          - gcc
          - git
          - build-essential
          - devscripts
       tags: dev
