     - name: Monitoring | Monitoring via munin will be installed
       action: apt pkg={{ item }} state=installed
       with_items:
          - munin
          - munin-node
          - munin-plugins-extra
          - libio-all-lwp-perl
       tags: monitoring 

     - name: Set munin-node config file
       action: template src=templates/munin-node.conf.j2 dest=/etc/munin/munin-node.conf owner=root group=root mode=0755
       tags: monitoring 

     - name: Set munin config file
       action: template src=templates/munin.conf.j2 dest=/etc/munin/munin.conf owner=root group=root mode=0755
       notify: restart munin
       tags: monitoring 

     - name: Monitoring | Grab munin plugins
       action: get_url url={{ item }} dest=/usr/share/munin/plugins/ mode=0755
       with_items:
          - https://raw.github.com/munin-monitoring/contrib/master/plugins/nginx/nginx-combined
          - https://raw.github.com/munin-monitoring/contrib/master/plugins/nginx/nginx_memory
          - https://raw.github.com/munin-monitoring/contrib/master/plugins/mysql/mysql_size_all
          - https://raw.github.com/munin-monitoring/contrib/master/plugins/mysql/mysql_report
          - https://raw.github.com/munin-monitoring/contrib/master/plugins/mysql/mysql_size_ondisk
          - https://raw.github.com/munin-monitoring/contrib/master/plugins/mysql/mysql_size_all
       tags: monitoring 

     - name: Monitoring | Activate plugins
       action: file src=/usr/share/munin/plugins/{{ item }} dest=/etc/munin/plugins/{{ item }} state=link
       with_items:
          - nginx-combined
          - nginx_memory
          - mysql_size_all
          - mysql_report
          - mysql_size_ondisk
          - mysql_size_all
       tags: monitoring

     - name: Monitoring | Correct hostname for munin
       shell: sed -e  "s/\[localhost.localdomain\]/[{{ansible_fqdn}}]/" /etc/munin/munin.conf
       tags: monitoring
  
     - name: Monitoring | Munin should be running
       action: service name=munin state=running
       tags: monitoring 


