     - name: Sites | Configuration file for our site
       action: template src=templates/000-ansible.j2 dest=/etc/apache2/sites-available/000-ansible
       tags: websites

#     - name: SSL | Create cert directory
#       file: path=/etc/apache2/crt state=directory owner=root mode=0644
#       tags: websites
#
#     - name: SSL | Copy ssl key
#       action: template src=templates/ssl.key dest=/etc/apache2/crt/ssl.key owner=root mode=0400
#       tags: websites
#
#     - name: SSL | Copy ssl cert
#       action: template src=templates/ssl.crt dest=/etc/apache2/crt/ssl.crt owner=root mode=0400
#       tags: websites
#       
     - name: Sites | Enable default site
       action: command /usr/sbin/a2ensite 000-ansible
       notify: restart apache2
       tags: websites